""" Vim as and IDE (2020 Talk)
filetype plugin indent on
syntax on
set backspace=start,eol,indent
"set hidden
set noswapfile

let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"
""" Vim as and IDE (2020 Talk)

" Spaces and Indentation
set shiftwidth=2
set tabstop=2

" Editor appearance
set shortmess=I " Don't give intro message when opening empty vim
set number relativenumber
set ruler
set number
set cursorline
set fillchars=vert:│
colorscheme gruvbox

"show invisible characters
set list
set listchars=nbsp:⦸
set listchars+=tab:▸‒
set listchars+=extends:⇝
set listchars+=precedes:⇜
set listchars+=trail:▨
set listchars+=eol:⌝

" Search
set ignorecase
set smartcase
set incsearch
set hlsearch

" Splitting
set splitright
set splitbelow

" Status Line
set statusline+=%#warningmsg#
set statusline+=%*

set wildmenu

