"IT WAS AUTOMATICALLY CREATED FROM ~/dotfiles

" Key (Re)mappings
let mapleader=","
imap jj <Esc>

" Stop using arrow keys in Vim
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" Explained in https://github.com/junegunn/vim-plug
call plug#begin('~/.vim/plugged')
" Look and Feel
Plug 'chriskempson/base16-vim'
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='gruvbox'

" General Features
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }

Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
nnoremap <silent> <leader><space> :Files<CR>

Plug 'tpope/vim-dispatch'

" Editing
Plug 'terryma/vim-multiple-cursors'
Plug 'tpope/vim-surround'

" Development
Plug 'tpope/vim-fugitive'

Plug 'editorconfig/editorconfig-vim'
let g:EditorConfig_exclude_patterns = ['fugitive://.*']

Plug 'nathanaelkane/vim-indent-guides'
Plug 'tpope/vim-commentary'
Plug 'airblade/vim-gitgutter'

" Language Specific
Plug 'tpope/vim-jdaddy'
Plug 'othree/xml.vim'

Plug 'plasticboy/vim-markdown'
let vim_markdown_preview_hotkey='<C-m>'

Plug 'udalov/kotlin-vim'
Plug 'ambv/black'
call plug#end()

" Plugin Configuration


" Spaces and Indentation
set shiftwidth=2
set tabstop=2
filetype plugin indent on

" Editor appearance
set shortmess=I " Don't give intro message when opening empty vim
set number relativenumber
set hidden
set ruler
set number
set cursorline
set fillchars=vert:│

"show invisible characters
set list
set listchars=nbsp:⦸
set listchars+=tab:▸‒
set listchars+=extends:⇝
set listchars+=precedes:⇜
set listchars+=trail:▨
set listchars+=eol:⌝

" Editing behaviour
set expandtab
set nofoldenable
set bs=2 " Make backspace work as expected
set formatoptions+=j

" Syntax Highlighting
syntax on
set termguicolors
colorscheme gruvbox
if &term =~ '256color'
    " disable Background Color Erase (BCE) so that color schemes
    " render properly when inside 256-color tmux and GNU screen.
    " see also http://snk.tuxfamily.org/log/vim-256color-bce.html
    set t_ut=
endif

" Status Line
set statusline+=%#warningmsg#
set statusline+=%*

" Splitting
set splitright
set splitbelow
set diffopt+=vertical

set shell=/usr/local/bin/zsh
