if [ -x /usr/libexec/path_helper ]; then
    declare PATH=""
    eval "$(/usr/libexec/path_helper -s)"
fi

if [ "$(uname -p)" = "arm" ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if which rbenv &> /dev/null; then
    export PATH="$HOME/.rbenv/bin:$PATH"
    # enable shims and auto-completion
    eval "$(rbenv init - zsh)"
fi

user_local="${HOME}/.local/bin"
if [ -x "$user_local" ]; then
    export PATH="$user_local:$PATH"
fi
